name: demo2
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          stepVar1: stepvalue1
        run: |
          echo "The value for stepvar1: $stepVar1"
      - name: step2
        run: echo "This is step ${{ vars.repovar1 }}"
      - name: step3
        run: echo "This is step ${{ secrets.reposec1 }}"